---
title: "Getting started with the SPLITT C++ library"
author: "Venelin Mitov"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- TODO Add the following to the header:

bibliography: REFERENCES.bib
-->

```{r setup, include = FALSE}
# Make results reproducible
set.seed(1)
knitr::opts_chunk$set(cache = FALSE)
options(digits = 4, width=120, scipen = 999)
```

# Before you start
Before you consider using the SPLITT C++ library, try to answer the following questions for yourself.

* Do you use pre-order or post-order traversal of a tree-like data-structure?

    If you don't understand what I mean, chances are that you simply do not need to deal with SPLITT at that point. The reason is that I wrote SPLITT to solve a very specific problem, which I've encountered many times during my doctoral studies: perform the same type of calculation for all nodes in a *big tree*, where each node is related to some specific data and the calculation for one node uses as input the result from the calculation performed on its *daughter nodes*. This is what I mean by *post-order traversal*. A  *pre-order traversal* is the same with only one difference -- replace the term *daughter nodes* with the term *parent node* in the sentence above. 

* Do you need the tree-traversal to be fast?

    This very much depends on how frequently do you need to perform the tree-traversal. If you only need to do it once or a couple of times with a given dataset, then I don't see much need of speeding this up. In my specific use-case, I needed to run a tree traversal millions of times and this was by far the heaviest computational operation during the analysis of the biological data at my disposal. It would not be an exaggeration, if I say that, without SPLITT, my PhD would have needed several more decades of computation time on a modern high performance computing cluster. This was reduced to a few months, thanks to the fast C++ implementation, based on SPLITT. 

* How big are your trees and how complex is your node traversal operation?

    When I said *big tree* I meant a tree of more than 100 tips, sometimes, more than 10000 tips. This is not a hard rule of thumb, but parallel traversal will have a performance benefit mostly on a big tree. This depends on other factors as well, such as the computational and memory complexity of the node traversal operation. If the tree is relatively small and the operation is very simple (e.g. the addition or multiplication of a few double-precision numbers), then it is very likely that using SPLITT in parallel mode would not be faster than using it in serial mode. Yet, using SPLITT might still be a good idea in this case if you currently have an implementation in a slowly interpreted language, such as R, and wish to have a faster C++ version - in this case a serial SPLITT-based implementation is probably going to be between 10 and 200 times faster than the R-version. 

# Prerequisites 

Here is what you need before you can start working with SPLITT:

* A C++11 compiler. So far I've been able to compile a SPLITT-based program on OS X and Linux using the following compilers:

    - clang++ version 6.0.0 on OS X. To my knowledge, this is the first version of clang++ that has the omp.h header, so it is possible to compile code using OpenMP. I am not an expert on the topic of C++ compilers, so I don't know how the clang++ compiler behaves on other systems. On my Mac OS X, I've installed this compiler as part of my R toolchain. I've found [these instructions](http://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-macos/) very helpful. In case the above link has become outdated, or you wish to use clang without R, maybe start by reading the [llvm project  home-page](http://llvm.org/).
    - Previous clang++ versions on OS X. Before installing clang++ v6.0.0, I've been able to compile SPLITT-code with earlier versions but these were not supporting OpenMP, so I was able to run SPLITT only in serial mode.
    - Intel compiler. Previously, I've been able to compile SPLITT-based code with the Intel compiler (Mac OS X and Linux). This compiler is likely to generate the fastest binary code running on Intel processors. You can try downloading the Intel compiler, following the instructions on the [Intel C++ compilers page](https://software.intel.com/en-us/c-compilers). 

* Optional: If you compile with OpenMP enabled (compile flag -fopenmp), then you need a copy of the omp shared library on your link path. On an OS X system, I've used the following:
    
    - Before R 3.5.0 was released, I used the libiomp5.dylib included with the Intel C++ compiler;
    - After R 3.5.0 was released, I've switched to the libomp.dylib included in R. On my system, this was available in /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/ as well as in /Library/Frameworks/R.framework/Resources/lib. 
    
* Optional: Rcpp and RcppArmadillo packages in R. Installing these packages will be needed if you wish to use SPLITT as a back-end for an R-package of your own.

# Compiling and running the PMM example
Being a software library SPLITT does not provide a high-level end-user interface. Rather, SPLITT is used via its application programming interface (API). In other words, you use the library by putting your application specific code at several locations in your code where SPLITT would expect it to be. The easiest way to do this is to start from an example and use it as a skeleton for your own code, i.e. replace the code in the example with your application specific data-types, and traversal operations. Below I will show one such example. 

## Downloading the example files from github

In a local directory save the following links with the same file-names:

* [SPLITT.h](https://raw.githubusercontent.com/venelin/SPLITT/master/src/SPLITT.h)
* [main.cpp](https://raw.githubusercontent.com/venelin/SPLITT/master/console-app/main.cpp) 
* [test-input.txt](https://raw.githubusercontent.com/venelin/SPLITT/master/console-app/test-input.txt)

## Compiling your code

Go to the directory with the downloaded files and execute the following command:

```{bash, eval=FALSE}
# Feel free to replace the name of the executable with your C++ compiler
clang++ -Wall -O2 -fopenmp -stdlib=libc++ -L/usr/local/lib -L/Library/Frameworks/R.framework/Resources/lib -o PMMLogLikelihood PMMLogLikelihood.cpp
```

This will compile and link the file main.cpp into an executable file called "main". If the compilation runs fine you should see no error messages.

## Testing the program

If the compilation was successful, type the following command.

```{bash, eval=FALSE}
./PMMLogLikelihood <input.txt
```

With the exceptino of the line starting with `"OpenMP-version:"`, the above command should produce the following output:

```{bash, eval=FALSE}
Hello from the SPLITT PMM example!
Reading the input tree from the standard input...
bonobo ancestor2 4.1
coalla ancestor3 5
gorilla ancestor1 2.8
dolfin ancestor1 3
human ancestor3 4
ancestor1 ancestor2 4.2
ancestor3 root 6
ancestor2 root 4.5
Reading the trait data from the standard input...
gorilla 1.8998
bonobo 0.9606
coalla -0.7435
dolfin 1.7947
human 0.4609
Node-name order in the OrderedTree:
0. bonobo
1. human
2. dolfin
3. coalla
4. gorilla
5. ancestor3
6. ancestor1
7. ancestor2
8. root
Main loop...
  Calculating a, b, c at the root for sigma=0.5 and sigmae=1
  a=-0.432535, b=0.630659, c=-8.21595
  LL(gM=0.1, sigma=0.5, sigmae=1): -8.15721
  Calculating a, b, c at the root for sigma=0.8 and sigmae=0.4
  a=-0.205491, b=0.285864, c=-9.09873
  LL(gM=1.5, sigma=0.8, sigmae=0.4): -9.13229
Main loop finished ...
OpenMP-version: 201107
Good bye!
```

If the OpenMP-version is equal to 0, then, most likely your compiler does not support OpenMP and the header "omp.h" was not available during compilation. If the OpenMP-version was a different number, then your compiler has an other Open MP version in it. If there have been other differences, e.g. the reported values for a, b and c are different, then there could be a problem, which I am not aware of. Please, report this in the [SPLITT issues list](https://github.com/venelin/SPLITT/issues).

# Next steps

The next goal is to understand what the PMMLogLikelihood program actually does. We will do this in two steps:

- First, we will learn how to define a `TraversalSpecification` class in the [Writing a traversal specification](https://venelin.github.io/SPLITT/articles/SPLITTTraversalSpecification.html) guide.
- Then, we will see how the `TraversalSpecification` class is used to create and execute a `TraversalTask` in the [Running a traversal](https://venelin.github.io/SPLITT/articles/SPLITTRunTraversal.html) guide.





