---
title: "Calling SPLITT from an R-package"
author: "Venelin Mitov"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Calling SPLITT from an R-package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: REFERENCES.bib
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{Rcpp, eval=FALSE, echo=TRUE}
#include <RcppArmadillo.h>
#include <R_ext/Rdynload.h>
    
#include "./AbcPMM.h"
    
// [[Rcpp::plugins("cpp11")]]
// [[Rcpp::plugins(openmp)]]
// [[Rcpp::depends(RcppArmadillo)]]

using namespace SPLITT;

ParallelPruningAbcPMM* CreateParallelPruningAbcPMM(
    Rcpp::List const& tree, vec const& x) {
  arma::umat branches = tree["edge"];
  uvec br_0 = arma::conv_to<uvec>::from(branches.col(0));
  uvec br_1 = arma::conv_to<uvec>::from(branches.col(1));
  vec t = Rcpp::as<vec>(tree["edge.length"]);
  uint num_tips = Rcpp::as<Rcpp::CharacterVector>(tree["tip.label"]).size();
  uvec node_names = Seq(uint(1), num_tips);
  typename ParallelPruningAbcPMM::DataType data(node_names, x);
  return new ParallelPruningAbcPMM(br_0, br_1, t, data);
}

RCPP_EXPOSED_CLASS_NODECL(ParallelPruningAbcPMM::TreeType)
RCPP_EXPOSED_CLASS_NODECL(ParallelPruningAbcPMM::TraversalSpecificationType)
RCPP_EXPOSED_CLASS_NODECL(ParallelPruningAbcPMM::AlgorithmType)
  
  
RCPP_MODULE(SPLITT__AbcPMM) {
  Rcpp::class_<ParallelPruningAbcPMM::TreeType::Tree> ( "SPLITT__AbcPMM__Tree" )
  .property("num_nodes", &ParallelPruningAbcPMM::TreeType::Tree::num_nodes )
  .property("num_tips", &ParallelPruningAbcPMM::TreeType::Tree::num_tips )
  .method("LengthOfBranch", &ParallelPruningAbcPMM::TreeType::Tree::LengthOfBranch )
  .method("FindNodeWithId", &ParallelPruningAbcPMM::TreeType::Tree::FindNodeWithId )
  .method("FindIdOfNode", &ParallelPruningAbcPMM::TreeType::Tree::FindIdOfNode )
  .method("FindIdOfParent", &ParallelPruningAbcPMM::TreeType::Tree::FindIdOfParent )
  .method("OrderNodes", &ParallelPruningAbcPMM::TreeType::Tree::OrderNodes )
  ;
  Rcpp::class_<ParallelPruningAbcPMM::TreeType>( "SPLITT__AbcPMM__OrderedTree" )
    .derives<ParallelPruningAbcPMM::TreeType::Tree> ( "SPLITT__AbcPMM__Tree" )
    .method("RangeIdPruneNode", &ParallelPruningAbcPMM::TreeType::RangeIdPruneNode )
    .method("RangeIdVisitNode", &ParallelPruningAbcPMM::TreeType::RangeIdVisitNode )
    .property("num_levels", &ParallelPruningAbcPMM::TreeType::num_levels )
    .property("ranges_id_visit", &ParallelPruningAbcPMM::TreeType::ranges_id_visit )
    .property("ranges_id_prune", &ParallelPruningAbcPMM::TreeType::ranges_id_prune )
  ;
  Rcpp::class_<ParallelPruningAbcPMM::AlgorithmType::ParentType> ( "SPLITT__AbcPMM__TraversalAlgorithm" )
    .property( "VersionOPENMP", &ParallelPruningAbcPMM::AlgorithmType::ParentType::VersionOPENMP )
    .property( "NumOmpThreads", &ParallelPruningAbcPMM::AlgorithmType::ParentType::NumOmpThreads )
  ;
  Rcpp::class_<ParallelPruningAbcPMM::AlgorithmType> ( "SPLITT__AbcPMM__AlgorithmType" )
    .derives<ParallelPruningAbcPMM::AlgorithmType::ParentType>( "SPLITT__AbcPMM__TraversalAlgorithm" )
  ;
  Rcpp::class_<ParallelPruningAbcPMM>( "SPLITT__AbcPMM" )
  .factory<Rcpp::List const&, vec const&>(&CreateParallelPruningAbcPMM)
  .method( "DoPruning", &ParallelPruningAbcPMM::TraverseTree )
  .property( "tree", &ParallelPruningAbcPMM::tree )
  .property( "spec", &ParallelPruningAbcPMM::spec )
  .property( "algorithm", &ParallelPruningAbcPMM::algorithm )
  ;
}
```


# Packages used
```{r create-references, echo=FALSE, include=FALSE, eval=TRUE}
treeProcessing <- c("ape")
data <- c("data.table")
poumm <- c("POUMM")
testing <- c("testthat")
boot <- c("boot")
 
packagesUsed <- c(treeProcessing, data, poumm, boot, testing)

printPackages <- function(packs) {
  res <- ""
  for(i in 1:length(packs)) {
    res <- paste0(res, paste0(packs[i], ' v', packageVersion(packs[i]), ' [@R-', packs[i], ']'))
    if(i < length(packs)) {
      res <- paste0(res, ', ')
    }
  }
  res
}

# Write bib information (this line is executed manually and the bib-file is edited manually after that)
#knitr::write_bib(packagesUsed, file = "./REFERENCES-R.bib")
```

Apart from base R functionality, the patherit package uses a number of 3rd party R-packages:

* For tree processing: `r printPackages(treeProcessing)`;
* For reporting: `r printPackages(data)`;
* For the POUMM and PP estimates: `r printPackages(c(poumm, boot))`;
* For testing: `r printPackages(testing)`.

# References

