# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name splittree
#' @title namespace splittree;
#' 
#' @description All functions and classes defined in the namespace splittree.
#' 
#' [[Rcpp::export]]
NULL

#' @name uint
#' @title typedef unsigned int uint;
#' @description a synonyme for the native type.
#' @family basic-types
NULL

#' @name uvec
#' @title typedef \href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{uint}> uvec;
#' @description a vectof of \link{uint}'s.
#' @family basic-types
NULL

#' @name vec
#' @title typedef \href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<double> vec;
#' @description a vectof of double's.
#' @family basic-types
NULL

#' @name bvec
#' @title typedef \href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<bool> bvec;
#' @description a vectof of bool's.
#' @family basic-types
NULL

#' @name Tree
#' 
#' @title template<class Node, class Length>class Tree
#' 
#' @description A generic C++ class defining the data structure and basic 
#'   operations with a tree. 
#' 
#' @section Template Arguments:
#' \describe{
#' \item{class Node}{see \code{\link{NodeType}}.}
#' \item{class Length}{see \code{\link{LengthType}}.}
#' }
#' 
#' @seealso \code{\link{OrderedTree}}
NULL

#' @name Tree::NodeType 
#' @title typedef Node NodeType;
#' @description A public typedef in class \code{\link{Tree}}. A synonym for the 
#'   template argument \code{Node}. Defines a 
#'   hash-able type such as \code{int} or 
#'   \code{\href{http://en.cppreference.com/w/cpp/string/basic_string}{std::string}}. 
#'   Specifically, this should be a type for which 
#'   \code{\href{http://en.cppreference.com/w/cpp/utility/hash}{std::hash}}
#'   specialization does exist. This is the application-specific node-type. The branches in the tree are defined as couples of nodes 
#'   (branch_start_node, branch_end_node).
#' @details
#'   During the construction of \code{Tree} object, the nodes are assigned 
#'   \code{unsigned int} ids from 0 to M-1 (M being the number of nodes in the
#'   tree). 
#'   
#' @aliases NodeType
#' @seealso \code{\link{Tree}} \code{\link{FindIdOfNode}}
NULL

#' @name Tree::LengthType
#'
#' @title typedef Length LengthType;
#'
#' @description A public typedef in class \code{\link{Tree}}. A synonym for the template
#'   argument Length. Defines a type that can be associated with a branch. Can
#'   be \code{double}, but also a composite of several attributes on a
#'   branch, such as a \code{double} length and an \code{int} color.
#' @aliases LengthType Tree.LengthType
#' @seealso \code{\link{Tree}}
NULL

#' @name Tree::Tree
#' 
#' @title Constructor for class Tree
#' 
#' @param branch_start_nodes \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const&}; 
#'   starting node for every branch in the tree.
#' @param branch_end_nodes \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const&}; ending 
#'   node for every branch in the tree; must be the same length as 
#'   branch_start_nodes.
#' @param branch_lengths \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{LengthType}> const&}; lengths 
#'   associated with the branches. Pass an empty vector for branch_lengths for 
#'   a tree without branch lengths (i.e. only a topology).
#' 
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::num_nodes
#' @title Number of nodes in a tree
#'  
#' @section Signature:
#' \code{\link{uint} Tree::num_nodes() const;}
#'  
#' @return the numbef of nodes in the tree, including tips, internal nodes and the root.
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::num_tips
#' 
#' @title Number of tips (a.k.a. leaves) in the tree
#' @section Signature:
#' \code{\link{uint} \link{Tree}::num_nodes() const;}
#' @return \code{\link{uint}}, the number of tips in the tree.
#' @seealso \code{\link{Tree}}
NULL

#' @name Tree::HasBranchLengths
#' 
#' @title Does a tree has lengths associated with its branches?
#' @section Signature:
#' \code{bool \link{Tree}::HasBranchLengths() const;}
#' @return \code{bool}, \code{true} if the tree has branch lengths.
#' @aliases HasBranchLengths
#' @family branch-length-methods
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::LengthOfBranch
#' 
#' @title Get the length of a branch ending at node with id \code{i}
#' @section Signature:
#' \code{\link{LengthType} const& \link{Tree}::LengthOfBranch(uint i) const;}
#' @param i \code{\link{uint}}; the id of the end-node for the branch
#' @return \code{\link{LengthType}}; the length associated with the branch ending at node \code{i}.
#' @aliases LengthOfBranch
#' @family branch-length-methods
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::BranchLengths
#' 
#' @title Get a reference to the internal vector of branch lengths.
#' @section Signature:
#' \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{LengthType}> const& \link{Tree}::BranchLengths() const;}
#' @return \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{LengthType}> const&}; 
#'   a const reference to the internally stored vector of branch lengths, in the order of the end-node ids.
#' @aliases BranchLengths
#' @family branch-length-methods
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::SetLengthOfBranch
#' 
#' @title Set the length of a branch ending at node with id \code{i} to a given \code{value}
#' @section Signature:
#' \code{void \link{Tree}::SetLengthOfBranch(uint i, \link{LengthType} const& value);}
#' @param i \code{\link{uint}}; the id of the end-node of the branch;
#' @param value \code{\link{LengthType} const&}; the new value of to set.
#' @return \code{void}
#' @family branch-length-methods
#' @aliases SetLengthOfBranch
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::SetBranchLengths
#' 
#' @title Set a new internally stored vector of branch lenthts
#' 
#' @description 
#' @section Signature:
#' \code{void \link{Tree}::SetBranchLengths(\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{LengthType}> const& lengths);}
#' @param lengths \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{LengthType}> const&}; 
#'   a const reference to a new vector of branch lengths, in the order of the end-node ids. 
#'   The vector should be of length M-1, where M is the 
#'   number of nodes in the tree.
#' @return \code{void}
#' @aliases SetBranchLengths
#' @family branch-length-methods
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::SetBranchLengths2
#' 
#' @title Set new branch lenthts to the branches in the order given by their 
#'   application-specific end-nodes.
#' @description If the tree has no branch lengths, the supplied arguments should
#'   be of length M-1, where M is the total number of nodes in the tree (-1, 
#'   because there is no branch leading to the root).
#' @section Signature:
#' \code{void \link{Tree}::SetBranchLengths(\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const& nodes_branch_ends, \href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{LengthType}> const& lengths);}
#' 
#' @param nodes_branch_ends \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const&}; 
#'   a const reference to a new vector of branch lengths, in the order of the nodes in \code{nodes_branch_ends}.
#' @param lengths \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{LengthType}> const&}; 
#'   a const reference to a new vector of branch lengths, in the order of the nodes in \code{nodes_branch_ends}.
#'   
#' @return \code{void}
#' @aliases SetBranchLengths
#' @family branch-length-methods
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::FindNodeWithId
#' @title Get the node with the specified id.
#' @section Signature:
#' \code{\link{NodeType} const& \link{Tree}::FindNodeWithId(uint id) const;}
#' 
#' @description A public method of class \code{\link{Tree}}.
#' 
#' @param id \code{\link{uint}} the id of the node (should be between 0 and M-1, where
#'   M is the number of nodes in hte tree).
#' @family node-methods  
#' 
#' @aliases FindNodeWithId
#' 
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::FindIdOfNode
#' @title Get the internally stored id of a node
#' 
#' @section Signature:
#' \code{uint \link{Tree}::FindIdOfNode(\link{NodeType} const& node) const;}
#' 
#' @description A public method of class \code{\link{Tree}}.
#' 
#' @param node \code{\link{NodeType} const&}; the node;
#' 
#' @return an \code{\link{uint}} from 0 to M-1, where M is the number of nodes 
#'   in the tree.
#' @family node-methods 
#' 
#' @aliases FindIdOfNode
#' 
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::FindIdOfParent
#' @title Get the parent id of a node with id id_child.
#' @section Signature:
#' \code{uint \link{Tree}::FindIdOfParent(uint id_child) const;}
#' 
#' @param id_child \code{\link{uint}}, the id of the child node. 
#' 
#' @return an \code{\link{uint}} from 0 to M-1, where M is the number of nodes 
#'   in the tree.
#'   
#' @family node-methods
#' 
#' @aliases FindIdOfParent
#'  
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::FindChildren
#' @title Get a vector with the ids of the children of a node.
#' @section Signature:
#' \code{uvec const& \link{Tree}::FindChildren(uint i) const;}
#' 
#' @param i \code{\link{uint}}; the id of a node. 
#' 
#' @return a \code{uvec const&}; a const reference to an internally stored vector of the
#'   ids of the children of \code{i}. If \code{i} is a tip, an empty uvec is returned. The
#'   returned vector reference is valid as long as the tree object is not destroyed.
#'   
#' @family node-methods 
#' 
#' @aliases FindChildren
#' 
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::OrderNodes
#' @title Reorder a vector of nodes
#' @section Signature:
#' \code{\link{uvec} \link{Tree}::OrderNodes(\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const& nodes) const;}
#' @param nodes \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const&}; 
#'   a vector of application-specific nodes.
#' @return \code{\link{uvec}}; a vector of positions in \code{nodes} in the order of 
#'   their internally stored ids.
#' @family node-methods
#' @aliases OrderNodes
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

#' @name Tree::OrderNodesPosType
#' @title Reorder a vector of nodes (generic w.r.t. the position type).
#' @section Template Arguments:
#' \describe{
#' \item{PosType}{an integer type for the positions in the returned vector.}}
#' @section Signature:
#' \code{template<class PosType> \href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<PosType> \link{Tree}::OrderNodesPosType(\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const& nodes, PosType const& NA) const;
#' @param nodes \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<PosType> \link{Tree}::OrderNodesPosType(\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<\link{NodeType}> const&}; 
#'   a vector of application-specific nodes.
#' @param NA \code{PosType const&}; NA value used mainly for the purpose of template-specification.
#' @return \code{\href{http://en.cppreference.com/w/cpp/container/vector}{std::vector}<PosType>}; a vector of positions in nodes in the order of their internally stored ids.
#' the element-type of the returned vector can be specified as a template argument or 
#' dedcued from the type of NA.
#' @aliases OrderNodesPosType
#' @family node-methods
#' @seealso \code{\link{Tree}} \code{\link{OrderedTree}}
NULL

